### ISSUE TITLE
StackOverflowError while preparing a statement

### ISSUE THREAD

**Issue by asoltysik** [tpolecat/skunk#148]
I tried to minimize the failing code:
```scala
object Main extends IOApp {

  val session: Resource[IO, Session[IO]] = ???

  def run(args: List[String]): IO[ExitCode] = session.use { s =>
    val list = List.fill(12000)("whatever")
    val values = text.values.list(list.length)

    val cmd = sql"VALUES $values".command

    s.prepare(cmd).use { ps => 
      IO.pure(ExitCode.Success)
    }
  }
```

Result:
```
ERROR java.lang.StackOverflowError
ERROR 	at scodec.bits.ByteVector.go$2(ByteVector.scala:230)
ERROR 	at scodec.bits.ByteVector.take(ByteVector.scala:237)
ERROR 	at scodec.bits.BitVector$.toBytes(BitVector.scala:1691)
ERROR 	at scodec.bits.BitVector$Bytes.take(BitVector.scala:1699)
ERROR 	at scodec.bits.BitVector$Bytes.take(BitVector.scala:1695)
ERROR 	at scodec.codecs.IntCodec.decode(IntCodec.scala:31)
ERROR 	at scodec.Decoder$$anon$2.decode(Decoder.scala:56)
ERROR 	at scodec.Decoder$$anon$2.decode(Decoder.scala:56)
ERROR 	at scodec.Decoder$$anon$2.$anonfun$decode$2(Decoder.scala:56)
ERROR 	at scodec.Attempt$Successful.flatMap(Attempt.scala:113)
ERROR 	at scodec.Decoder$$anon$2.decode(Decoder.scala:56)
ERROR 	at scodec.Decoder$$anon$2.decode(Decoder.scala:56)
ERROR 	at scodec.Decoder$$anon$2.$anonfun$decode$2(Decoder.scala:56)
ERROR 	at scodec.Attempt$Successful.flatMap(Attempt.scala:113)
ERROR 	at scodec.Decoder$$anon$2.decode(Decoder.scala:56)
ERROR 	at scodec.Decoder$$anon$2.decode(Decoder.scala:56)
ERROR 	at scodec.Decoder$$anon$2.$anonfun$decode$2(Decoder.scala:56)
ERROR 	at scodec.Attempt$Successful.flatMap(Attempt.scala:113)
ERROR 	at scodec.Decoder$$anon$2.decode(Decoder.scala:56)
ERROR 	at scodec.Decoder$$anon$2.decode(Decoder.scala:56)
ERROR 	at scodec.Decoder$$anon$2.$anonfun$decode$2(Decoder.scala:56)
... and so on
```

**Comment by tpolecat** [comment]
My guess is that it's blowing up decoding the row description. I'm using `replicateA` to do it [here](https://github.com/tpolecat/skunk/blob/master/modules/core/src/main/scala/net/message/RowDescription.scala#L37) and that may not be right. @mpilquist does it make sense that this would blow up, and is there a better way to do it?

**Comment by mpilquist** [comment]
Try:

```scala
  val decoder: Decoder[RowDescription] =
    codecs.listOfN(int16, Field.decoder.as[RowDescription])
```

**Comment by tpolecat** [comment]
Excellent, thanks! @asoltysik I'll take a PR if you want to make this change (with a test case!) otherwise I'll get to it at some point.

**Comment by asoltysik** [comment]
Sure, will do near the weekend.

**Comment by asoltysik** [comment]
> Looks like it's blowing up decoding the row description

**Comment by tpolecat** [comment]
Ok, no worries. Thanks!
