### ISSUE TITLE
Error when restart postgres

### ISSUE THREAD

**Issue by tolikbotov** [tpolecat/skunk#383]
I use `Session.pooled`. When app starts i acquire pool. And then on each db operation i do `pool.use(session.execute(...))`.

If postgres instance restarted on next request application stops with error:

```
╠─An unchecked error was produced.
║ scala.MatchError: NetworkError(java.lang.Exception: Fatal: Read 0 bytes, expected 5.) (of class skunk.net.BufferedMessageSocket$NetworkError)
║       at skunk.net.protocol.Query$$anon$1.$anonfun$finishUp$1(Query.scala:40)
║       at zio.internal.FiberContext.evaluateNow(FiberContext.scala:914)
║       at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:776)
║       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
║       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
║       at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by tolikbotov** [comment]
Maybe this is duplication of #81

**Comment by tolikbotov** [comment]
If i just drop session in database. I saw in log:

**Comment by tolikbotov** [comment]
On db i see this:
```
aurinko=> select * from pg_stat_activity where datname = 'db_name';
 datid |      datname      |  pid  | leader_pid | usesysid | usename  | application_name | client_addr | client_hostname | client_port |         backend_start         |          xact_start           |          query_start          |         state_change          | wait_event_type | wait_event |        state        | backend_xid | backend_xmin |   query    |  backend_type  
-------+-------------------+-------+------------+----------+----------+------------------+-------------+-----------------+-------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-----------------+------------+---------------------+-------------+--------------+------------+----------------
 27732 | db_name | 75965 |            |    17008 | postgres |                  | 127.0.0.1   |                 |       53158 | 2021-02-18 14:14:47.739525+03 | 2021-02-18 14:28:41.094386+03 | 2021-02-18 14:28:41.094489+03 | 2021-02-18 14:28:41.094496+03 | Client          | ClientRead | idle in transaction |             |              | UNLISTEN * | client backend
(1 row)

```

**Comment by tpolecat** [comment]
Thanks for the report. Need better handling for broken sockets.
