### ISSUE TITLE
Microsite out of date

### ISSUE THREAD

**Issue by matthughes** [tpolecat/skunk#713]
Microsite doesn't seem to reflect the latest release.  It shows 0.2.3 when latest is 0.3.2.  

I tried my hand at building the site with docs/paradox on clean checkout but got the following error:

```
sbt:skunk> docs/paradox
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] Copy resource mappings:
[debug]
[error] Unexpected top-level pages (pages that do no have a parent in the Table of Contents).
[error] If this is intentional, update the `paradoxRoots` sbt setting to reflect the new expected roots.
[error] Current ToC roots: []
[error] Specified ToC roots: [index.html]
[error] Paradox failed with 1 errors
[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 755 products, 142 sources, 19 libraries
[debug] current source = Set(${BASE}/modules/core/shared/src/main/scala/net/message/Close.scala, ${BASE}/modules/core/shared/src/main/scala/net/protocol/Exchange.scala, ${BASE}/modules/core/shared/src/main/scala-2.13+/data/ArrPlatform.scala, ${BASE}/modules/core/shared/src/main/scala/data/Identifier.scala, ${BASE}/modules/core/shared/src/main/scala/util/Text.scala, ${BASE}/modules/core/shared/src/main/scala/exception/TooManyParametersException.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/AuthenticationSASL.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/NoData.scala, ${BASE}/modules/core/shared/src/main/scala/net/protocol/Close.scala, ${BASE}/modules/core/shared/src/main/scala/AppliedFragment.scala, ${BASE}/modules/core/shared/src/main/scala/Transaction.scala, ${BASE}/modules/core/shared/src/main/scala/Command.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/SASLInitialResponse.scala, ${BASE}/modules/core/shared/src/main/scala/net/protocol/Describe.scala, ${BASE}/modules/core/shared/src/main/scala/exception/UnexpectedDataException.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/PasswordMessage.scala, ${BASE}/modules/core/shared/src/main/scala/net/protocol/Prepare.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/BackendMessage.scala, ${BASE}/modules/core/jvm/src/main/scala/net/message/PasswordMessagePlatform.scala, ${BASE}/modules/core/shared/src/main/scala-2/syntax/StringContextOps.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/CopyFail.scala, ${BASE}/modules/core/shared/src/main/scala/util/Pretty.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/AuthenticationSSPI.scala, ${BASE}/modules/core/shared/src/main/scala/Statement.scala, ${BASE}/modules/core/shared/src/main/scala/net/protocol/Unroll.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/Describe.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/ParameterDescription.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/ParameterStatus.scala, ${BASE}/modules/core/shared/src/main/scala/Cursor.scala, ${BASE}/modules/core/jvm/src/main/scala/net/protocol/StartupPlatform.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/CopyOutResponse.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/PortalSuspended.scala, ${BASE}/modules/core/shared/src/main/scala/exception/UnexpectedColumnsException.scala, ${BASE}/modules/core/shared/src/main/scala/net/protocol/package.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/Bind.scala, ${BASE}/modules/core/shared/src/main/scala/codec/AllCodecs.scala, ${BASE}/modules/core/shared/src/main/scala/syntax/ListOps.scala, ${BASE}/modules/core/shared/src/main/scala/net/BufferedMessageSocket.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/EmptyQueryResponse.scala, ${BASE}/modules/core/shared/src/main/scala/Query.scala, ${BASE}/modules/core/shared/src/main/scala/Codec.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/ErrorResponse.scala, ${BASE}/modules/core/shared/src/main/scala/exception/StartupException.scala, ${BASE}/modules/core/shared/src/main/scala/exception/ProtocolError.scala, ${BASE}/modules/core/shared/src/main/scala/exception/CopyNotSupportedException.scala, ${BASE}/modules/core/shared/src/main/scala-2/SqlState.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/NoticeResponse.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/ReadyForQuery.scala, ${BASE}/modules/core/shared/src/main/scala/data/TransactionIsolationLevel.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/AuthenticationSASLContinue.scala, ${BASE}/modules/core/shared/src/main/scala/exception/NoDataException.scala, ${BASE}/modules/core/shared/src/main/scala/Void.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/Flush.scala, ${BASE}/modules/core/shared/src/main/scala/exception/EmptyStatementException.scala, ${BASE}/modules/core/shared/src/main/scala/package.scala, ${BASE}/modules/core/shared/src/main/scala/net/protocol/Bind.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/BackendKeyData.scala, ${BASE}/modules/core/shared/src/main/scala/data/Completion.scala, ${BASE}/modules/core/shared/src/main/scala/util/Typer.scala, ${BASE}/modules/core/shared/src/main/scala/exception/SCRAMProtocolException.scala, ${BASE}/modules/core/shared/src/main/scala/util/StatementCache.scala, ${BASE}/modules/core/shared/src/main/scala/exception/UnknownOidException.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/AuthenticationSASLFinal.scala, ${BASE}/modules/core/shared/src/main/scala/PreparedQuery.scala, ${BASE}/modules/core/shared/src/main/scala-2.13/utll/package.scala, ${BASE}/modules/core/shared/src/main/scala/exception/UnsupportedAuthenticationSchemeException.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/RowData.scala, ${BASE}/modules/core/shared/src/main/scala/Channel.scala, ${BASE}/modules/core/shared/src/main/scala/net/protocol/Execute.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/AuthenticationGSSContinue.scala, ${BASE}/modules/core/shared/src/main/scala/net/BitVectorSocket.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/SASLResponse.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/AuthenticationSCMCredential.scala, ${BASE}/modules/core/shared/src/main/scala/exception/ColumnAlignmentException.scala, ${BASE}/modules/core/shared/src/main/scala/exception/SkunkException.scala, ${BASE}/modules/core/shared/src/main/scala/Fragment.scala, ${BASE}/modules/core/shared/src/main/scala/data/TransactionAccessMode.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/CloseComplete.scala, ${BASE}/modules/core/shared/src/main/scala/net/protocol/Query.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/NotificationResponse.scala, ${BASE}/modules/core/shared/src/main/scala/data/TransactionStatus.scala, ${BASE}/modules/core/shared/src/main/scala/net/AbstractMessageSocket.scala, ${BASE}/modules/core/shared/src/main/scala/exception/UnsupportedSASLMechanismsException.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/CopyData.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/Parse.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/Execute.scala, ${BASE}/modules/core/jvm/src/main/scala/SSLPlatform.scala, ${BASE}/modules/core/shared/src/main/scala/util/Origin.scala, ${BASE}/modules/core/shared/src/main/scala/Encoder.scala, ${BASE}/modules/core/shared/src/main/scala/codec/UuidCodec.scala, ${BASE}/modules/core/shared/src/main/scala/exception/DecodeException.scala, ${BASE}/modules/core/shared/src/main/scala/util/Namer.scala, ${BASE}/modules/core/shared/src/main/scala/data/Arr.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/AuthenticationGSS.scala, ${BASE}/modules/core/shared/src/main/scala/data/SemispaceCache.scala, ${BASE}/modules/core/shared/src/main/scala/util/Recycler.scala, ${BASE}/modules/core/shared/src/main/scala/codec/BinaryCodecs.scala, ${BASE}/modules/core/shared/src/main/scala/net/package.scala, ${BASE}/modules/core/shared/src/main/scala/net/SSLNegotiation.scala, ${BASE}/modules/core/shared/src/main/scala/exception/UnknownTypeException.scala, ${BASE}/modules/core/shared/src/main/scala/codec/TextCodecs.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/Terminate.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/package.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/AuthenticationOk.scala, ${BASE}/modules/core/shared/src/main/scala/net/Protocol.scala, ${BASE}/modules/core/shared/src/main/scala-2/syntax/AllOps.scala, ${BASE}/modules/core/shared/src/main/scala/PreparedCommand.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/Sync.scala, ${BASE}/modules/core/shared/src/main/scala/exception/EofException.scala, ${BASE}/modules/core/shared/src/main/scala-2/codec/EnumCodecPlatform.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/CommandComplete.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/AuthenticationRequest.scala, ${BASE}/modules/core/shared/src/main/scala/Session.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/AuthenticationMD5Password.scala, ${BASE}/modules/core/shared/src/main/scala/codec/NumericCodecs.scala, ${BASE}/modules/core/shared/src/main/scala/data/Notification.scala, ${BASE}/modules/core/shared/src/main/scala/SSL.scala, ${BASE}/modules/core/shared/src/main/scala/net/protocol/Startup.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/ParseComplete.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/CopyInResponse.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/UnknownMessage.scala, ${BASE}/modules/core/shared/src/main/scala/net/protocol/Parse.scala, ${BASE}/modules/core/shared/src/main/scala/data/TypedRowDescription.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/FrontendMessage.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/RowDescription.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/StartupMessage.scala, ${BASE}/modules/core/shared/src/main/scala/util/Pool.scala, ${BASE}/modules/core/shared/src/main/scala/Decoder.scala, ${BASE}/modules/core/shared/src/main/scala/codec/BooleanCodec.scala, ${BASE}/modules/core/shared/src/main/scala/syntax/IdOps.scala, ${BASE}/modules/core/shared/src/main/scala-2/util/Twiddler.scala, ${BASE}/modules/core/shared/src/main/scala/codec/EnumCodec.scala, ${BASE}/modules/core/shared/src/main/scala/exception/PostgresErrorException.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/CopyDone.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/BindComplete.scala, ${BASE}/modules/core/shared/src/main/scala/net/MessageSocket.scala, ${BASE}/modules/core/shared/src/main/scala/exception/package.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/AuthenticationKerberosV5.scala, ${BASE}/modules/core/shared/src/main/scala/data/Type.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/Query.scala, ${BASE}/modules/core/shared/src/main/scala/codec/TemporalCodecs.scala, ${BASE}/modules/core/shared/src/main/scala/net/message/AuthenticationCleartextPassword.scala)
[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[debug] No changes
[debug] Created transactional ClassFileManager with tempDir = /Users/MHughe008/Opensource/skunk/modules/core/jvm/target/scala-2.13/classes.bak
[debug] Removing the temporary directory used for backing up class files: /Users/MHughe008/Opensource/skunk/modules/core/jvm/target/scala-2.13/classes.bak
[error] (docs / Compile / paradoxMarkdownToHtml) com.lightbend.paradox.sbt.ParadoxPlugin$ParadoxException
[error] Total time: 0 s, completed Sep 26, 2022, 9:56:44 AM
```

How is the site built / published to GH Pages?

**Comment by armanbilge** [comment]
> How is the site built / published to GH Pages?

I think it's been published manually, IDK.

Best thing long-term is probably to migrate to sbt-typelevel-site.

https://typelevel.org/sbt-typelevel/site.html

**Comment by tpolecat** [comment]
iirc it's `docs/makeSite` and then `docs/ghpagesPushSite`

**Comment by matthughes** [comment]
Just putting notes for myself to investigate later that makeSite results in:

```
sbt:skunk> docs/makeSite
[info] compiling 2 Scala sources to /Users/MHughe008/Opensource/skunk/modules/docs/target/scala-2.13/classes ...
[info] running mdoc.Main --no-link-hygiene
info: Compiling 18 files to /Users/MHughe008/Opensource/skunk/modules/docs/target/mdoc
error: Command.md:286:1: Connection refused
CommandExample.run(Nil).unsafeRunSyncWithRedirect()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:256)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:202)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217)
	at java.base/sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:312)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at async_ @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.$anonfun$client$7(SocketGroupPlatform.scala:61)
	at blocking @ com.comcast.ip4s.DnsCompanionPlatform$$anon$1.resolve(DnsPlatform.scala:27)
	at map @ com.comcast.ip4s.SocketAddressCompanionPlatform$ResolveOps.resolve(SocketAddressPlatform.scala:39)
	at flatMap @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.connect$1(SocketGroupPlatform.scala:60)
	at delay @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.$anonfun$client$4(SocketGroupPlatform.scala:57)
	at onError @ skunk.util.Pool$.$anonfun$of$3(Pool.scala:93)
	at delay @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.setup$1(SocketGroupPlatform.scala:54)
	at make @ skunk.util.Pool$.of(Pool.scala:164)
	at make @ skunk.util.Pool$.of(Pool.scala:164)
info: Compiled in 5.04s (1 error)
[info] shutting down sbt server
```

**Comment by mpilquist** [comment]
Site was republished for 0.3.2 release
